[package]
name = "example-exex-rollup"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
# reth
reth.workspace = true
reth-chainspec.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-node-ethereum.workspace = true
reth-primitives.workspace = true
reth-execution-errors.workspace = true
reth-execution-types.workspace = true
reth-provider.workspace = true
reth-revm.workspace = true
reth-tracing.workspace = true

# async
tokio.workspace = true

# misc
alloy-consensus = { workspace = true, features = ["kzg"] }
alloy-genesis.workspace = true
alloy-rlp.workspace = true
alloy-sol-types = { workspace = true, features = ["json"] }
eyre.workspace = true
foundry-blob-explorers = "0.1"
once_cell.workspace = true
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde_json.workspace = true

[dev-dependencies]
reth-testing-utils.workspace = true
secp256k1.workspace = true

