[package]
name = "reth-rpc-engine-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Implementation of Engine API"

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-provider.workspace = true
reth-rpc-types.workspace = true
reth-rpc-api.workspace = true
reth-beacon-consensus.workspace = true
reth-payload-builder.workspace = true
reth-tasks.workspace = true
reth-rpc-types-compat.workspace = true
reth-engine-primitives.workspace = true

# async
tokio = { workspace = true, features = ["sync"] }

# metrics
reth-metrics.workspace = true
metrics.workspace = true

# misc
async-trait.workspace = true
thiserror.workspace = true
jsonrpsee-types.workspace = true
jsonrpsee-core.workspace = true
tracing.workspace = true
serde.workspace = true

[dev-dependencies]
reth-ethereum-engine-primitives.workspace = true
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-payload-builder = { workspace = true, features = ["test-utils"] }
reth-tokio-util.workspace = true

alloy-rlp.workspace = true

assert_matches.workspace = true

[features]
optimism = ["reth-primitives/optimism"]
